  name: Test Runner Image
  
  on:
    workflow_dispatch:
  
  jobs:
    build:
      strategy:
        matrix:
          os: [ubuntu-20.04, ubuntu-22.04]
      runs-on: ${{ matrix.os }}
      steps:
        - name: test mysqldump
          shell: bash
          run: |
             sudo service mysql start
             mysql -s -N -h localhost -uroot -proot -e "CREATE USER 'user12'@'localhost' IDENTIFIED WITH mysql_native_password BY 'Pass12';"
             mysql -s -N -h localhost -uroot -proot -e "CREATE DATABASE testdb12; SHOW CREATE DATABASE testdb12; USE testdb12; CREATE TABLE Persons (PersonID int, LastName varchar(255), FirstName varchar(255), Address varchar(255), City varchar(255));"
             mysql -s -N -h localhost -uroot -proot -e "GRANT ALL PRIVILEGES ON testdb12.* to 'user12'@'localhost';"
             mysql -s -N -h localhost -uroot -proot -e "GRANT USAGE ON *.* TO 'user12'@'localhost';"
             mysql -s -N -h localhost -uroot -proot -e "GRANT PROCESS ON *.* TO 'user12'@'localhost';"
             echo "starting mysqldump to backup testdb12 to testdb.sql"
             mysqldump -uuser12 -pPass12 testdb12 > ./testdb.sql
             ls -la ./testdb.sql
           
